# Generated by Django 5.2.3 on 2025-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.CharField(blank=True, choices=[('pleine', 'Pleine'), ('vide', 'Vide')], max_length=10, null=True)),
                ('file_size_kb', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('avg_red', models.IntegerField(blank=True, null=True)),
                ('avg_green', models.IntegerField(blank=True, null=True)),
                ('avg_blue', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
